# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: veli++
email: velitasali@protonmail.com
publisher: veli tasalı
description: > # this means to ignore newlines until "baseurl:"
  A weapon as powerful as a towel
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://velitasali.github.io" # the base hostname & protocol for your
github_username:  velitasali

# Build settings
markdown: kramdown
